# Generated by Django 3.2.16 on 2022-11-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20221121_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'фидбэк', 'verbose_name_plural': 'фидбэки'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='mail',
            field=models.EmailField(default='1@example.com', help_text='Максимум 254 символа', max_length=254, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='', help_text='Максимум 150 символов', max_length=150, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(verbose_name='фидбэк'),
        ),
    ]
