# Generated by Django 3.2.16 on 2022-11-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'допольнительное поле', 'verbose_name_plural': 'допольнительные поля'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, default='10.10.2000', null=True, verbose_name='день рождения'),
        ),
    ]
