# Generated by Django 3.2.16 on 2022-12-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'рейтинг', 'verbose_name_plural': 'рейтинги'},
        ),
    ]
