# Generated by Django 3.2.16 on 2022-10-29 16:30

import catalog.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonFieldsNameIsPublished',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This attribute keeps\n                            the name of the entry', max_length=150, verbose_name='Название')),
                ('is_published', models.BooleanField(default=True, help_text='This attribute keeps\n                                       information whether the entry\n                                       has been published', verbose_name='Опубликовано')),
            ],
        ),
        migrations.CreateModel(
            name='CommonFieldsSlugNameIsPublished',
            fields=[
                ('commonfieldsnameispublished_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.commonfieldsnameispublished')),
                ('slug', models.SlugField(help_text='This attribute keeps\n                            the url of the entry', max_length=200, unique=True, verbose_name='Адрес')),
            ],
            bases=('catalog.commonfieldsnameispublished',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('commonfieldsslugnameispublished_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.commonfieldsslugnameispublished')),
                ('weight', models.PositiveSmallIntegerField(default=100, help_text='This attribute keeps\n                                              the weight of the category', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вес')),
            ],
            bases=('catalog.commonfieldsslugnameispublished',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('commonfieldsslugnameispublished_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.commonfieldsslugnameispublished')),
            ],
            bases=('catalog.commonfieldsslugnameispublished',),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('commonfieldsnameispublished_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.commonfieldsnameispublished')),
                ('text', models.TextField(help_text='This attribute keeps\n                            the description of the item', validators=[catalog.validators.validate_amazing], verbose_name='Описание')),
                ('category', models.ForeignKey(help_text='This attribute keeps\n                                 the category of the item', on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(help_text='This attribute keeps\n                                  the tags that belong to item', to='catalog.Tag', verbose_name='Тэг')),
            ],
            bases=('catalog.commonfieldsnameispublished',),
        ),
    ]
