# Generated by Django 3.2.16 on 2022-10-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='test'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='test', max_length=150),
        ),
    ]
