# Generated by Django 3.2.16 on 2022-11-08 20:24

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20221108_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='name',
            field=models.CharField(help_text='Максимум 150 символов', max_length=150, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='Описание должно содержать слова "роскошно" и "превосходно"', validators=[catalog.validators.validate_amazing], verbose_name='описание'),
        ),
    ]
