# Generated by Django 3.2.16 on 2022-10-30 23:26

import catalog.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_item_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='Описание должно быть больше, чем\n                             из двух символов и содержать слова "роскошно,\n                             превосходно"', validators=[catalog.validators.validate_amazing, django.core.validators.MinLengthValidator(2)], verbose_name='Описание'),
        ),
    ]
