# Generated by Django 3.2.16 on 2022-11-09 06:42

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20221108_2024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Galery',
            new_name='Gallery',
        ),
        migrations.AlterField(
            model_name='item',
            name='preview',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.preview', verbose_name='превью'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='Описание должно содержать слова "роскошно" и "превосходно"', validators=[catalog.validators.validate_amazing], verbose_name='описание'),
        ),
    ]
