# Generated by Django 3.2.16 on 2022-11-01 19:35

import catalog.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20221031_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Максимум 150 символов', max_length=150, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(help_text='Выберите категорию', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Максимум 150 символов', max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='Описание должно содержать слова "роскошно" и "превосходно".', validators=[catalog.validators.validate_amazing], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Максимум 150 символов', max_length=150, unique=True, verbose_name='Название'),
        ),
    ]
