# Generated by Django 3.2.16 on 2022-11-09 17:52

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_item_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='preview',
        ),
        migrations.AddField(
            model_name='preview',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.item', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(help_text='Максимум 150 символов', max_length=150, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='Описание должно содержать слова "роскошно" и "превосходно"', validators=[catalog.validators.validate_amazing], verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='preview',
            name='name',
            field=models.CharField(help_text='Максимум 150 символов', max_length=150, verbose_name='название'),
        ),
    ]
