# Generated by Django 3.2.16 on 2022-12-05 10:17

import catalog.validators
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_item_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='оценка'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=ckeditor.fields.RichTextField(help_text='Описание должно содержать слова "роскошно" и "превосходно"', validators=[catalog.validators.validate_amazing], verbose_name='описание'),
        ),
    ]
