# Generated by Django 3.2.16 on 2022-11-09 18:50

import catalog.validators
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_item_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='previews/%Y/%m/%d', verbose_name='превью товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=ckeditor.fields.RichTextField(help_text='Описание должно содержать слова "роскошно" и "превосходно"', validators=[catalog.validators.validate_amazing], verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='preview',
            name='image',
            field=models.ImageField(upload_to='previews/%Y/%m/%d', verbose_name='превью товара'),
        ),
    ]
