# Generated by Django 3.2.16 on 2022-11-11 20:55

import catalog.validators
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20221109_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='name',
        ),
        migrations.RemoveField(
            model_name='preview',
            name='name',
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=ckeditor.fields.RichTextField(help_text='Описание должно содержать слова "роскошно" и "превосходно"', validators=[catalog.validators.validate_amazing], verbose_name='описание'),
        ),
    ]
