# Generated by Django 3.2.16 on 2022-11-21 22:53

import catalog.validators
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_item_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preview',
            new_name='MainImage',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'default_related_name': 'items', 'ordering': ['name'], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=ckeditor.fields.RichTextField(help_text='Описание должно содержать слова "роскошно" и "превосходно"', validators=[catalog.validators.validate_amazing], verbose_name='описание'),
        ),
    ]
